#ifndef __TCPCONST__
#define __TCPCONST__

#define ARP_BROAD_REQ 1
#define ARP_REPLY 2
#define ARP_MESSAGE 806
# define ETH_IP 0x0800
#define ARP_BROADCAST_MAC 0xFFFFFFFFFFFF
#define VLAN_8021Q_PROTO 0x8100
#define MAX_VLAN_MEMBERSHIP 10




#endif /* __TCPCONST__ */